#!/usr/bin/env perl
use strict;
use autodie;
use Getopt::Long;
use Cwd;
my $h=0;
GetOptions ('help' => \$h, 'h' => \$h);
if ($h==1 || $ARGV[0] eq ""){ # If asked for help or did not set up any argument
	print "# Script to prepare the table of runs for the database
# Arguments :
# run
";
	die "\n";
}


my $in_file="Runs_to_ecosystem_and_sequencing_and_study.tsv";
my $lib_file="Run_list_with_results_nr.tsv";
my $out_file="Runs_to_ecosystem_and_sequencing_and_study_for_db.tsv";
my $final_red="final_reduction.tsv";

my $check_file="test_list_libs_from_spacertbl.tsv";
## Generated by: cat Data/All_spacers_info_filtered-Jul19-24.tsv | gawk -F '\t' '{print $8}' | sort | uniq > test_list_libs_from_spacertbl.tsv

my %expected;
open my $tsv,"<",$check_file;
while(<$tsv>){
    chomp($_);
    if ($_ eq "library"){next;}
    $expected{$_}=1;
}
close $tsv;

my %translate;
open my $tsv,"<",$final_red;
while(<$tsv>){
    chomp($_);
    my @tab=split("\t",$_);
    if ($tab[0] eq "Eco_base"){next;}
    # $translate{$tab[1]}{"2"}=$tab[2];
    $translate{$tab[0]}{"3"}=$tab[1];
}
close $tsv;

my %seen_prev;
my %sra_run_to_lib;
open my $tsv,"<",$lib_file;
while(<$tsv>){
    chomp($_);
    my @tab=split("\t",$_);
    my $test=$tab[0]."_".$tab[5]."_".$tab[6]."_".$tab[7];
    if (defined($seen_prev{$test})){
        print "We already saw $test\n";
    }
    else{
        $seen_prev{$test}=1;
        $sra_run_to_lib{$tab[0]}{$tab[1]}=1;
    }
}
close $tsv;

my %tmp;
my %excluded_sample;
open my $s1,">",$out_file;
open my $tsv,"<",$in_file;
while(<$tsv>){
    chomp($_);
    my @tab=split("\t",$_);
    if ($tab[0] eq "SRA_run"){
        print $s1 "library\tsra_run\tecosystem_base\tecosystem_sum\tbiofilm\tsequencing_platform\tbioproject\tbiosample\tn_spot\tn_base\ttitle\n";
    }
    else{
        if ($tab[1]=~/Exclude/){
            print "Excluding $tab[0]\n";
            $excluded_sample{$tab[0]}=1;
        }
        else{
            if ($#tab==7){
                ## No title, fill in
                $tab[8]="NA";
            }
            %tmp=();
            if (defined($sra_run_to_lib{$tab[0]})){
                foreach my $lib (keys %{$sra_run_to_lib{$tab[0]}}){
                    if ($lib=~/^(.*)\.\d+$/){$lib=$1;}
                    if (defined($tmp{$lib})){
                        print $tab[0]."\t".$lib."\talready added\n";
                    }
                    else{
                        print $s1 $lib."\t".$tab[0]."\t".$tab[1]."\t".$translate{$tab[1]}{"3"}."\t".join("\t",@tab[2..$#tab])."\n";
                        $expected{$lib}=2;
                        $tmp{$lib}=1;
                    }
                }
            }
            else{
                print "No library processed for sra Run ".$tab[0]."\t".$tab[1]."\t".$translate{$tab[1]}{"3"}."\t".join("\t",@tab[2..$#tab])."\n";
                print "We ignore\n";
                # die("\n");
            }
        }
    }
}
close $tsv;
close $s1;


foreach my $lib (sort keys %expected){
    if ($expected{$lib}==1){
        if ($excluded_sample{$lib}==1){
            print "### $lib -> We have CRISPR spacers, but the sample was excluded (e.g. it was a blank)\n";
        }
        else{
            print "### $lib -> We have CRISPR spacers, but no sample info ?\n";
        }
    }
}